export const SET_ALL_NEWS="SET_ALL_NEWS"
export const SET_NEWS_BY_SOURCE="SET_NEWS_BY_SOURCE"
export const GET_NEWS_SOURCE="GET_NEWS_SOURCE"
export const GET_ALL_SOURCE="GET_ALL_SOURCE"
export const SET_TOP_NEWS='SET_TOP_NEWS'